### ISSUE TITLE
making Blitz part of Boost?

### ISSUE THREAD

**Issue by slayoo** [blitzpp/blitz#46]
Just wondering what would be the pros and cons?

Certainly, it would clarify the way to go with docs, build system, boost dependencies (serialization, MPI, preprocessor), packaging issues, etc

Some legal clarifications would need to be done (but perhaps with benefit for Blitz).
Blitz would definitely benefit from Boost review process.
Boost folks might be interested given the Boost.MultiArray seems outdated, the overlap with Boost.ublas seems unclear.

Any thoughts?

**Comment by citibeth** [comment]
Blitz is not up to the standards required for boost.  I would like to write
a new blitz that is

**Comment by citibeth** [comment]
Blitz++ doesn't follow normal C++ semantics, that is the problem.  It acts
sort of like a value, and sort of like a shared_ptr.  It cannot be put in a
collection.  These are the reasons I don't think the current version would
be a good fit for Boost.  I think these problems can be fixed with some
thinking through and starting with C++11.

-- Elizabeth

**Comment by vukics** [comment]
By the way, this subject [came up already](https://sourceforge.net/p/blitz/mailman/message/22899392/) in the blitz++ SF mailing list.
It did not generate much echo apart from a [brief reaction ](https://sourceforge.net/p/blitz/mailman/message/22918502/)by myself.

**Comment by slayoo** [comment]
Given the above and the b11 initiative (#48), let me close this one fully agreeing with @citibeth that it's much more practical to concentrate efforts there.
