### ISSUE TITLE
Installed Blitz with spack: What to do next?

### ISSUE THREAD

**Issue by ClmnsRck** [blitzpp/blitz#99]
This is basically a request to everyone how has sufficient know-how and rights to do this. 
Please either write a detailed doc on how to install and use this library, that isn't outdated, or simplify the installation process to a bare minimum.

I am currently trying my best to install and use `Blitz++`, as it would help me in my work and it seems to be a great lib for Tensor-Computation. The problem is, that after installing `spack` and using it to install `Blitz++`, i now don't know how to proceed. I am basically missing the know-how about `spack, c++ and lib-linking/usage, Linux and unix in general`(here i should mention, that if you dont understand most of the terminology, you cant even really google the stuff, because you either dont no what to look for, or get overwhelmed by the amount of new information, which might or might not be relevant to your issue). For a library this sophisticated, it should not be a problem to somehow make the "product" available for everyone. Your are basically gate-keeping yourself from inexperienced developers, trying to approach this library. I am sorry if this comes off as a rant, but spending half a week to install a library does not feel right.

The sad thing is, i basically asked this question on Monday and got told to use spack ... and after that was a bit lost.

Sry for the long "meta"-post but i wanted to get this of my chest. Have a nice day.

**Comment by slayoo** [comment]
Just for the record, there is an ongoing effort to build up a Blitz wiki with such information, see here: https://github.com/blitzpp/blitz/wiki 
Contributions welcome!

**Comment by ClmnsRck** [comment]
Maybe i should mention, that i still cant get it to work ... spack installed blitz, but how do i "call" the library. The Documentation by the Uni Graz suggest commadline-calls that do not seem to work.

And that i do not wish to belittle your efforts, just trying to explain the problem from the perspective of a absolute beginner.

**Comment by slayoo** [comment]
BTW, here's also a list of Blitz packages available for different platforms: https://github.com/blitzpp/blitz/wiki/Package-availability

**Comment by slayoo** [comment]
Concerning how to use it, on the Features wiki page: https://github.com/blitzpp/blitz/wiki/Features
after clicking on any of the non-TODO-labelles examples, you can see a short code snipped along with commands and output. HTH

**Comment by slayoo** [comment]
P.S. I have no experience with spack

**Comment by ClmnsRck** [comment]
Thank you for your help, but with this code Snippet:
```
0001: #include <blitz/array.h>
0002: #include <iostream>
0003: 
0004: int main(){
0005: 	blitz::Array<double, 3> A(2,2,2);
0006: 	return 0;
0007: }
```
And this compiler call: `g++ main.cpp`

I get this: 
```
main.cpp:1:10: fatal error: blitz/array.h: No such file or directory
 #include <blitz/array.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
```
And `sudo apt install libblitz0v5` tells me, that it is actually already installed(if that is what you suggested when you told me about the Package-availability)

**Comment by citibeth** [comment]
> Please either write a detailed doc on how to install and use this library,
> that isn't outdated, or simplify the installation process to a bare minimum.
>

Blitz++ uses Autotools, which (along with CMake) is one of the two
widely-used, standardized ways to package and distribute software.  When
packages follow these standards (as Blitz++ does), then package authors do
not need to provide detailed instructions on how to use these standard
tools.  There is plenty of documentation around the web on how to install
Autotools-based packages.  Maybe Blitz++ could link to some of that; but
there is no need to give a detailed Autotools tutorial (nor would we be the
best person to write such a tutorial).

> The problem is, that after installing spack and using it to install
> Blitz++, i now don't know how to proceed. I am basically missing the
> know-how about spack, c++ and lib-linking/usage, Linux and unix in general(here
> i should mention, that if you dont understand most of the terminology, you
> cant even really google the stuff, because you either dont no what to look
> for, or get overwhelmed by the amount of new information, which might or
> might not be relevant to your issue).
>
I understand that there is a big learning curve for building and installing
software on Linux.  That's why most of my colleagues are not able to make
effective use of the open source software available --- because they don't
know how to get it built and installed.  It's a big problem.  After doing a
lot by hand, I came to believe that auto-builders are the future.  After
researching multiple auto-builders, I decided that Spack was the one that
best fit my needs.  That was 3yr ago, when Spack built about 250 packages.
Now it does over 2000 (3000?).  It's come a long way.

If you've installed Blitz++, that's half the battle!  Now you just need to
learn how to use it.  There was a thread on that issue just a couple of
days ago:
   https://github.com/spack/spack/issues/3295

You can also read the Spack manual.  It's not complete or perfect; but a
LOT of work has gone into it, and there's a lot there.
  https://spack.readthedocs.io/en/latest/

Then take any questions you have to the Spack mailing list:
   https://groups.google.com/forum/#!forum/spack

There's a LOT of experience on that list, and you WILL get your questions
answered.  I'm active in Spack and might answer the questions myself.
Along the way, you will probably get the chance to move up the learning
curve on how software building, linking, etc. works.  It's a problem that
should be simple but turns out to be really complicated and difficult.

> For a library this sophisticated, it should not be a problem to somehow
> make the "product" available for everyone. Your are basically gate-keeping
> yourself from inexperienced developers, trying to approach this library. I
> am sorry if this comes off as a rant, but spending half a week to install a
> library does not feel right.
>
Your time is not wasted.  If you learn what you need to install Blitz++,
then you'll be able to install any other Autotools-based package the same
way.  If you do it with Spack, you'll be able to install a lot of other
packages as well, without having to know all the details.

(PS: I've spent that same half week fixing obscure problems building
`autoconf`, `curl`, `numpy`, `scipy` on our supercomputer.  The `git` I
built runs but doesn't do anything.  And this is ALL stuff that built just
fine on my desktop.  I agree, this is not fun.)

Sorry, but I don't know of any easier ways to learn how to build from
source, other than to say that Spack folks are really nice and really
helpful.  At least Blitz++ is relatively simple (since it has no
dependencies).

I suppose we could provide OS-specific RPMs.  But I have no experience in
that, and do not have the time to maintain them.

-- Elizabeth

>

**Comment by slayoo** [comment]
In Debian, libblitz0-dev package contains the headers, and puts them into /usr/include
(https://packages.debian.org/sid/amd64/libblitz0-dev/filelist)

I guess doing ```find / -name array.h''' will tell you where spack has placed the headers

**Comment by citibeth** [comment]
ClmnsRck,

Please take this question to the Spack mailing list, and I WILL answer it
there.  This is really really basic stuff that's the same for any package
or library you use (it's also not specific to Spack; but I will answer it
on the Spack list).

https://groups.google.com/forum/#!forum/spack

-- Elizabeth

**Comment by ClmnsRck** [comment]
One last question, actually regarding the development of Blitz++:
Why isnt it possible to implement Blitz++ as a header-only library? 
Eigen: http://eigen.tuxfamily.org/index.php?title=Main_Page and Fastor: https://github.com/romeric/Fastor both somehow did it, would this be possible for Blitz++? That would probably solve my issue :sweat_smile:

**Comment by citibeth** [comment]
On Thu, Feb 21, 2019 at 10:17 AM ClmnsRck <notifications@github.com> wrote:

> One last question, actually regarding the development of Blitz++:
> Why isnt it possible to implement Blitz++ as a header-only library?
>
Simple answer is, I don't know.  I didn't write Blitz++.  The original
authors put it on SourceForge and abandoned it, and the library slowly got
out of date.  But it "just works" so well, that this wasn't a big problem.
But SourceForge became really dodgy, and I became afraid we could lose this
critical piece of software.  Eventually I tracked down the authors and got
them to help me transfer the repo to GitHub.  Slayoo came on and added some
much-needed attention to Blitz++ as well.

Eigen is newer than Blitz++, and based a lot of its techniques on the
Blitz++ effort.  However, Eigen doesn't do what Blitz++ does, so I wasn't
able to just use Eigen.  I would like a C++11 version of Blitz++ array
functionality; just need time to write it.  In the meantime, Blitz works
well enough and there's no realistic replacement (for my needs).

> Eigen: http://eigen.tuxfamily.org/index.php?title=Main_Page and Fastor:
> https://github.com/romeric/Fastor both somehow did it, would this be
> possible for Blitz++? That would probably solve my issue 😅
>
Or just learn how to install and link to libraries that are not
header-only.  You'll be glad you know how to do that.

-- Elizabeth

**Comment by ClmnsRck** [comment]
Ok, i did not know that. Thank you for your help, i got i to work now.

**Comment by slayoo** [comment]
Well, let me just add that Blitz is a header-only library. Linking with libblitz is only needed for debugging.

**Comment by citibeth** [comment]
BTW, the following just came through the NetCDF list.  Stuff like this comes through all the time.  This is what I'm trying to avoid by recommending Spack.
```
Hi,

I am trying to install NetCDF on my Ubuntu 18.04. for C++ to use 
.nc-files in my code for further calculations. Until now, I have 
installed curl, zlib, hdf 5 and the actual version of NetCDF-C 
(netcdf-c-4.6.2).
I have tested NetCDF-C on an example file (simple_xy_wr.c from 
https://www.unidata.ucar.edu/software/netcdf/examples/programs/) which 
compiles and runs without any problems.

After that, I wanted to install NetCDF for C++. Therefore, I downloaded 
the actual library (netcdf-cxx4-4.3.0.) and tried to configure the 
unpacked library by following command:

./configure --prefix=$fld_install --enable-cxx-4 ($fld_install is my 
directory where I want to install NetCDF-C++)

Unfortunately, I receive following warning after configuring the library:

configure: WARNING: unrecognized options: --enable-cxx-4

The same error occurs by trying –enable-netcdf-4.

After installing the library with the make & make install procedure, I 
can not compile any C++ code which contains some NetCDF-C++ -Data 
Structures.
I am not able to find any error in my approach and are pretty sure that 
my paths of NetCDF-C are set correctly. Maybe I got a wrig version 
combination of NetCDF-C and NetCDF-C++ or forgot something by 
configuring the libraries.

I would be very thankful for any help or hint of you where I have made a 
mistake by installing NetCDF-C or NetCDF-C++. Thank you for your help in 
advance.

With best regards
Markus
```

**Comment by papadop** [comment]
Just a small note. Blitz is indeed mostly header only. The lib is needed only for some facilities (not only for debugging): mostly global constants such as columnMajorArray, and index placeholders... blitz was conceived a long time ago. I believe we can suppress the lib totally by just making these symbol constexpr but that requires requiring a C++-11 compiler, which is not a big constraint in my opinion. There are several outdated guard in the code for earlier weaker C++ implementations which are also obsolete... In brie, there is a lot of cleanup that can be done if we require a fairly old C++ version (but much newer than C++ in the years 1998-2000).

**Comment by citibeth** [comment]
If we're going to do cleanup for C++11, then IMHO we should change the API
to be C++ compliant.  Right now you cannot, for example, have a collection
of blitz::Array.

**Comment by MicheleBe** [comment]
IMHO it Will be better to do it in two steps. Conversion to c++11 or 14 and
update api with deprecate the old ones.  This will also give opportunity to
easy migrate to the new version for someone using the old implementation.

**Comment by ClmnsRck** [comment]
What does this error mean?
```
spack install blitz
==> Installing blitz
==> Searching for binary cache of blitz
==> Warning: No Spack mirrors are currently configured
==> No binary for blitz found: installing from source
==> Using cached archive: /home/ruck/spack/var/spack/cache/blitz/blitz-1.0.1.tar.gz
==> Staging archive: /home/ruck/spack/var/spack/stage/blitz-1.0.1-55uu5roueihntaq7mwviuhzcci2q7eqk/1.0.1.tar.gz
==> Created stage in /home/ruck/spack/var/spack/stage/blitz-1.0.1-55uu5roueihntaq7mwviuhzcci2q7eqk
==> No patches needed for blitz
==> Building blitz [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j20' 'lib'
See build log for details:
  /home/ruck/spack/var/spack/stage/blitz-1.0.1-55uu5roueihntaq7mwviuhzcci2q7eqk/blitz-1.0.1/spack-build.out
```
I didnt want to open another issue, but this happend on instaling blitz on a new system.

**Comment by ClmnsRck** [comment]
Added it. Spack also cant install libelf, though i dont know if that is important here.

**Comment by citibeth** [comment]
I can't find the *spack-build.out* file anywhere.  Please attach it to an
email or issue or something, and rename to *.txt* while doing so.  Your
Blitz++ error is described inside that file.
